Contact form
sumairq/Personal-Portfolio pull request #3
Opened 2021-11-30 19:26 UTC by sumairq

# Added the following

- Html for contact form.
- Styles for contact form.
- Background illustration for contact form.

2021-11-30 20:02 UTC, rotimiazeez requested changes
# Hi Team👋, 
![](https://media.giphy.com/media/cYaB1VycDbOyOiXcCx/giphy.gif)
### Good job so far!👏
### There are some issues that you still need to work on to go to the next project but you are almost there!
> Kindly make the suggested changes and you'll be unstoppable🎉🎉✔
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-30 20:02 UTC, rotimiazeez commented on index.html
> +  </section>
- [ ] Kindly wrap the `contact` section in a `footer` tag to make your code more readable, understandable and semantic 😉👍

2021-11-30 20:02 UTC, rotimiazeez commented on index.html
> +        </li>
- [ ] Please note that the form inputs are not a list items, your code will be more readable if you use👇
 ``` 
   <div id="contact-list">
     <input>
     <input>
     <textarea>
     <button></button>
     </div>
```

2021-11-30 20:02 UTC, rotimiazeez commented on index.html
> +          <textarea name="message" required maxlength="500">Enter text here</textarea>
- [ ] Kindly add required to the `textarea` to make sure it's validated 😉

2021-12-01 16:30 UTC, HENRYKC24 approved these changes
## Hi @sumairq:wave:, 
# STATUS: APPROVED :heavy_check_mark: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-01 16:34 UTC, merged